Repository openebs/jiva-csi, pull requests merged in 2020-02, with the labels that each got.

#13 fix(jiva-csi): fix rbac permission issues
  deploy/jiva-csi-ubuntu-16.04.yaml
  deploy/jiva-csi.yaml
Labels: bug

#14 refact(make): add push script to push container image
  .travis.yml
  Makefile
  build/push
Labels: enhancement

#10 feat(jiva-csi): Add JivaVolumePolicy schema changes
  .travis.yml
  ci/ci.sh
  deploy/jiva-csi.yaml
  go.mod
  go.sum
  pkg/driver/controller.go
  pkg/jivavolume/jivavolume.go
  pkg/kubernetes/client/client.go
Labels: enhancement, feature

#15 fix(travis): remove exit 0 from policy create
  ci/ci.sh
Labels: bug

#16 fix(jiva-csi): dealock in monitor mount goroutine
  pkg/driver/mount.go
Labels: bug

#18 doc(changelog): add changelog for 1.7.0-RC1
  CHANGELOG.md
Labels: documentation
